### ISSUE TITLE
Migrate to Netlify

### ISSUE THREAD

**Issue by mithintv** [mithin888/wordle-tracker-client#3]
#### Tasks
- [x] Update api endpoints on client
- [x] Migrate to netlify
- [x] Update environmental variables
